# Generated by Django 4.0 on 2022-01-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
    ]
