# Generated by Django 4.0 on 2022-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='', upload_to='teachers_image/')),
            ],
        ),
    ]
